language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
before_script:
  - mv config/travis.database.yml config/database.yml
  - mv config/travis.application.yml config/application.yml
  - psql -c 'create database my_app_test' -U postgres
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
