carnival_floats:
  2016:
    -
      image: '2016.jpg'
      text: '<p>Nachdem sich unser Wagen seit dem Jahr 2013 nicht erwähnenswert verändert hatte &ndash; es wurden andere Ideen verwirklicht
             &ndash; musste zu unserem <strong>11-jährigen</strong> ein Paukenschlag her.</p>
             <p>Mehr Mitglieder und mehr Kamelle forderten mehr
             Platz auf mehr Etagen. Für die Kleinsten unten, damit es auch was zu gucken gibt. Für die Großen auf einem
             Podest und hoch oben über den Köpfen der Jecken.</p>
             <p>Die harte Arbeit des Wagenbau-Teams wurde durch eine Live-Band
             &ndash; <a href="http://koelschroyal.de/">Kölsch Royal</a> belohnt. Damit sah der neue Wagen nicht nur
             enorm schick aus. Er klang auch einmalig. Pures Gänsehautfeeling</p>'

  2015:
    -
      image: '2015.jpg'
      text: ''
  2014:
    -
      image: '2014.jpg'
      text: ''

  2013:
    -
      image: '2013.jpg'
      text: 'Im Jahr 2013 erschien unser Karnevalswagen in neuem Glanz: Ein neuer Anstrich in rot und weiß – und unser
             Wagen erstrahlt in den kölschen Farben.'

  2012:
    -
      image: '2012.jpg'
      text: 'Im Jahr 2012 gingen wir natürlich wieder beim Wahner Zug mit – zusätzlich beteiligten wir uns zum ersten
             Mal auch beim Porzer Zug. Das wollen wir 2015 zu unserem zehnjährigen Jubiläum wiederholen!'

  2011:
    -
      image: '2011.jpg'
      text: 'Nach kleineren Reparaturen und Ausbesserungen sah unser Wagen wieder wie neu aus. Auch in diesem Jahr
             liefen wir wieder beim Wahner Zug mit.'

  2010:
    -
      image: '2010.jpg'
      text: 'Regen, Schnee, Hagel? Schön ist das an Karneval zwar alles nicht, aber wir standen ab diesem Jahr im
             Trockenen: Unser Karnevalswagen hat ein Dach bekommen.'
  2009:
    -
      image: '2009.jpg'
      text: 'Dekoration heißt das Zauberwort: In diesem Jahr verschönerten wir unseren Karnevalswagen  und ließen unsere
             künstlerische Ader walten.'
  2008:
    -
      image: '2008.jpg'
      text: 'In den letzten Monaten steckten wir ganz viel Zeit und Mühe in den Bau unseres Wagens. In diesem Jahr
             gingen wir zum ersten Mal beim Wahner Zug mit unserem eigenen Wagen. Ein großer Erfolg für die Wahner
             Kölschbusters!'
  2007:
    -
      image: '2007.jpg'
      text: '2007 war es dann soweit: Zum ersten Mal gingen wir beim Wahner Zug mit. Wir fuhren mit einem echten
             amerikanischen Schulbus, den wir uns geliehen hatten.'
    -
      image: '2007-2.jpg'
      text: 'Im Jahr 2007 gab es noch einen weiteren Meilenstein für die Kölschbusters: Wir kauften unseren zukünftigen
             Karnevalswagen. Auf geht’s an die Arbeit!'
  2006:
    -
      image: '2006.jpg'
      text: 'Auch 2006 versammelte sich der Verein am Wahner Zugrand. In diesem Jahr bekam der Wagen ein neues Dach,
             damit die Einlagerung einfacher wurde.'
  2005:
    -
      image: '2005.jpg'
